### ISSUE TITLE
Does not work on MSWin32

### ISSUE THREAD

**Issue by plicease** [plicease/Alien-flex#1]
copying text from last comment in

https://github.com/Perl5-Alien/Alien-Base/issues/93

Adding `--disable-shared` to the `configure` command helps.

Also flex uses regex.h and -lregex ... I was able to build this from this source:

http://sourceforge.net/projects/mingw/files/Other/UserContributed/regex/mingw-regex-2.5.1/

Unfortunately, flex itself uses a number of POSIXisms that are going to be a problem:

```
libtool: link: gcc -g -O2 -o flex.exe ccl.o dfa.o ecs.o scanflags.o gen.o main.o misc.o nfa.o parse.o scan.o skel.o sym.o tblcmp.o yylex.o options.o scanopt.o buf.o tables.o tables_shared.o filter.o regex.o  lib/.libs/libcompat.a
main.o: In function `flex_main':
N:\home\ollisg\dev\Alien-flex\Alien-flex-0.01\_alien\flex-2.5.39/main.c:168: undefined reference to `wait'
N:\home\ollisg\dev\Alien-flex\Alien-flex-0.01\_alien\flex-2.5.39/main.c:169: undefined reference to `WIFEXITED'
N:\home\ollisg\dev\Alien-flex\Alien-flex-0.01\_alien\flex-2.5.39/main.c:168: undefined reference to `wait'
N:\home\ollisg\dev\Alien-flex\Alien-flex-0.01\_alien\flex-2.5.39/main.c:170: undefined reference to `WEXITSTATUS'
tables.o: In function `yytbl_write32':
N:\home\ollisg\dev\Alien-flex\Alien-flex-0.01\_alien\flex-2.5.39/tables.c:289: undefined reference to `htonl'
tables.o: In function `yytbl_write16':
N:\home\ollisg\dev\Alien-flex\Alien-flex-0.01\_alien\flex-2.5.39/tables.c:308: undefined reference to `htons'
filter.o: In function `filter_apply_chain':
N:\home\ollisg\dev\Alien-flex\Alien-flex-0.01\_alien\flex-2.5.39/filter.c:159: undefined reference to `pipe'
N:\home\ollisg\dev\Alien-flex\Alien-flex-0.01\_alien\flex-2.5.39/filter.c:162: undefined reference to `fork'
filter.o: In function `filter_tee_header':
N:\home\ollisg\dev\Alien-flex\Alien-flex-0.01\_alien\flex-2.5.39/filter.c:332: undefined reference to `wait'
filter.o: In function `filter_fix_linedirs':
N:\home\ollisg\dev\Alien-flex\Alien-flex-0.01\_alien\flex-2.5.39/filter.c:416: undefined reference to `regexec'
N:\home\ollisg\dev\Alien-flex\Alien-flex-0.01\_alien\flex-2.5.39/filter.c:365: undefined reference to `regexec'
regex.o: In function `flex_regcomp':
N:\home\ollisg\dev\Alien-flex\Alien-flex-0.01\_alien\flex-2.5.39/regex.c:56: undefined reference to `regcomp'
N:\home\ollisg\dev\Alien-flex\Alien-flex-0.01\_alien\flex-2.5.39/regex.c:66: undefined reference to `regerror'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [flex.exe] Error 1
make[2]: Leaving directory `/n/home/ollisg/dev/Alien-flex/Alien-flex-0.01/_alien/flex-2.5.39'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/n/home/ollisg/dev/Alien-flex/Alien-flex-0.01/_alien/flex-2.5.39'
make: *** [all] Error 2
```

Some of those missing symbols I think are just missing because configure isn't detecting -lregex correctly.  But things like `fork` are much more problematic.

**Comment by vikasnkumar** [comment]
I had to add `alien_bin_requires` for `Alien::m4` and `Alien::bison` to be picked up in `inc/My/ModuleBuild.pm`.

**Comment by plicease** [comment]
https://github.com/Perl5-Alien/Alien-Base/issues/93#issuecomment-63727286

@vikasnkumar what is the name of the Debian package?  Ideally a native build would be best.

**Comment by plicease** [comment]
I don't think flex needs bison to build?  But m4 is definitely a requirement.

**Comment by plicease** [comment]
This may be useful too, though caveats a plenty with using MinGW stuff with strawberry:

http://sourceforge.net/projects/mingw/files/MSYS/Extension/flex/flex-2.5.35-2/

**Comment by vikasnkumar** [comment]
- Is this tarball something to use instead of the regular 2.5.39 that Alien::flex is downloading and testing ?
- I looked at the flex 2.5.4 code present in the GnuWin32 and they do not have the wait/WIFEXITED POSIX stuff so we could technically patch that portion with `#ifndef WIN32` since they seem to be doing signal handling there.

**Comment by plicease** [comment]
I was hoping the mingw port might provide some hints as to what exactly the correct patch should be, but I'm not entirely sure that it helps.  I do see they have a fix for the -lregex probing that seems to be missing.

their patch requires re-running autotools though since they are patching `configure.in` though, so it isn't directly usable by `Alien::flex`.

**Comment by plicease** [comment]
This fixes some of the missing symbol errors:

https://github.com/plicease/Alien-flex/commit/998b1038cfcf26d6a6d12d2c9b0394cf3b26bf8c

Not sure what to do about `fork` and `wait`.  Still not obvious to me how they managed to get it to work in the mingw version.

**Comment by plicease** [comment]
One thing that you may want to try is shipping with an already generated scanner.  Also may want to check that the package isn't already shipping a generated scanner that just needs its timestamp updated.

**Comment by vikasnkumar** [comment]
Good point. I will check this.

**Comment by plicease** [comment]
Going to close this as "flex not supported on MSWin32"  if this ever changes we can revisit.

**Comment by plicease** [comment]
Also I am going to go ahead and release to CPAN as it may still be useful for those not on Windows :)

**Comment by vikasnkumar** [comment]
Yes no problem. I am not using it anyway now. Forcing the user to use
the Windows installer for the app instead and checking for that.
